SELECT 
F.NOME,
E.NATUREZA,
SUM(L.VALOR)
FROM FUNCIONARIOS F
INNER JOIN LANCAMENTOS_FOLHA L ON F.ID_FUNC = L.ID_FUNC
INNER JOIN EVENTOS_FOLHA E ON L.ID_EVENTO = E.ID_EVENTO
GROUP BY F.NOME, E.NATUREZA
ORDER BY F.NOME;